/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Files;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.sql.*;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP
 */
public class meeting extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    
    
    /**
     * Creates new form meeting
     */
    public meeting() {
        initComponents();
        
        section();
        DisableCheck();
        
    }

    
    private void DisableCheck(){
        
        loc_check.disable();
        int_check.disable();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        search = new javax.swing.JPanel();
        searchme = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        print_rec = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lpic1 = new javax.swing.JLabel();
        f_name = new javax.swing.JTextField();
        l_name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gender_cmb = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ht = new javax.swing.JTextField();
        mt_cmb1 = new javax.swing.JComboBox();
        dat = new javax.swing.JTextField();
        panel4 = new java.awt.Panel();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        con_cmb = new javax.swing.JComboBox();
        txt_amount = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        v_table = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        yr_cmb = new javax.swing.JComboBox();
        loc_check = new javax.swing.JRadioButton();
        dba = new com.toedter.calendar.JDateChooser();
        int_check = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DYNAMIC GENERAL MEETING CONTRIBUTION");

        panel1.setBackground(new java.awt.Color(255, 51, 102));

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("Contact: 0540218787 || Email:wanzima100@gmail.com");

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("This Software is developed by Wanzima Technology Service");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/dynamic.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/dynamic.jpg"))); // NOI18N
        jLabel5.setText("jLabel3");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8))
        );

        search.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GENERAL MEETING CONTRIBUTION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 24), new java.awt.Color(0, 51, 255))); // NOI18N

        searchme.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        searchme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchmeActionPerformed(evt);
            }
        });
        searchme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchmeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchmeKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel6.setText("DYNAMIC CODE:");

        print_rec.setBackground(new java.awt.Color(255, 153, 0));
        print_rec.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        print_rec.setText("PRINT");
        print_rec.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        print_rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_recActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton3.setText("RECORDS");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 153, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton5.setText("BACK");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 153, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton4.setText("PAY");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchme, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(print_rec, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(164, 164, 164))
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchme, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print_rec, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERSONAL INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 24), new java.awt.Color(0, 0, 153))); // NOI18N

        lpic1.setBackground(new java.awt.Color(102, 102, 102));
        lpic1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lpic1.setOpaque(true);

        f_name.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        f_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        l_name.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        l_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel8.setText("FIRST NAME: ");

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel9.setText("LAST NAME: ");

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel10.setText("DATE OF BIRTH:");

        gender_cmb.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        gender_cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT GENDER", "MALE", "FEMALE", "OTHER" }));
        gender_cmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel15.setText("MARITAL STATUS:");

        jLabel18.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel18.setText("GENDER:");

        jLabel21.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel21.setText("HOME TOWN:");

        ht.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        ht.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htActionPerformed(evt);
            }
        });

        mt_cmb1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        mt_cmb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SINGLE", "MARRIED", " " }));
        mt_cmb1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        dat.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        dat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gender_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mt_cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(f_name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(l_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                            .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ht, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lpic1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lpic1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(gender_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mt_cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ht, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        panel4.setBackground(new java.awt.Color(102, 255, 255));
        panel4.setName(""); // NOI18N

        jButton9.setBackground(new java.awt.Color(255, 255, 51));

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("   DYNAMIC INTERNATIONAL CLUB, KUMASI BRANCH");

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GENERAL MEETING CONTRIBUTION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 24), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel2.setName("DYNAMIC GENERAL MEETING CONTRIBUTION"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel11.setText("FUNERAL");

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel13.setText("DATE :");

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel12.setText("CONTRIBUTION");

        con_cmb.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        con_cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DUES", "FUNERAL", "GIFT", "LIFE PREMIUM", "DONATION", "BIRTHDAY", "OTHER...", " " }));
        con_cmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        con_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_cmbActionPerformed(evt);
            }
        });

        txt_amount.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_amount.setText("GH ₵  ");
        txt_amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amountActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel14.setText("AMOUNT :  ");

        v_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        v_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DATE", "TYPE", "AMOUNT", "MEMBER FUNERAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(v_table);

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel16.setText("YEAR");

        yr_cmb.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        yr_cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", " " }));
        yr_cmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        loc_check.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loc_check.setText("LOCAL ");
        loc_check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loc_checkMouseEntered(evt);
            }
        });
        loc_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loc_checkActionPerformed(evt);
            }
        });

        dba.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        dba.setDateFormatString("yyyy-MM-dd");
        dba.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        int_check.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        int_check.setText("INTERNATIONAL");
        int_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int_checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(yr_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(20, 20, 20)
                                .addComponent(con_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(loc_check)
                                        .addGap(18, 18, 18)
                                        .addComponent(int_check))
                                    .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dba, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yr_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(con_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loc_check)
                    .addComponent(int_check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dba, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(94, 94, 94)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1170, 958));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchmeActionPerformed

    private void searchmeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchmeKeyReleased

        try {
            con=Connection1.ConnectDB();
            String sql = "Select * from member Where mem_id=?";

            pst=con.prepareStatement(sql);

            pst.setString(1, searchme.getText());
            rs=  pst.executeQuery();
            if (rs.next()){

                String add1=rs.getString("fname");
                f_name.setText(add1);

                String add3=rs.getString("lname");
                l_name.setText(add3);

                String com200=rs.getString("m_status");
                mt_cmb1.addItem(com200);

                String add2=rs.getString("dob");
                dat.setText(add2);

                String add110=rs.getString("city");
                ht.setText(add110);

                byte[] img = rs.getBytes("photo");

                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(lpic1.getWidth(), lpic1.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                lpic1.setIcon(newImage);

                String com10=rs.getString("gender");
                gender_cmb.addItem(com10);

            }
             else{
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Member Code, Does Not Exist !!", "No Data Found",JOptionPane.ERROR_MESSAGE);
               }


        }catch( Exception ex){

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_searchmeKeyReleased

    private void print_recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_recActionPerformed

        String value = l_name.getText();
        String value1 = f_name.getText();
        String value2 = searchme.getText();
        String value3 = ht.getText();
      
        JFileChooser dailog = new JFileChooser();
        dailog.setSelectedFile(new File(value+" "+value1+" Funeral Reciept"+".pdf"));
        int dialogResult = dailog.showSaveDialog(null);
        if (dialogResult == JFileChooser.APPROVE_OPTION) {
            String filepath = dailog.getSelectedFile().getPath();
        
            
          try {
               con = Connection1.ConnectDB();
               String sql = " Select * from general where mem_id='"+value2+"'";
              pst = con.prepareStatement(sql);
              rs = pst.executeQuery();
              
              while (rs.next()) {
              
               //String amt = rs.getString(5);
               //int amount = Integer.parseInt(amt);
              
              
               
               Document document = new Document();
               PdfWriter.getInstance(document, new FileOutputStream(filepath));
               document.open();
             
                   
                document.add(new Paragraph("                  DYNAMIC INTERNATIONAL CLUB, KUMASI BRANCH", FontFactory.getFont(FontFactory.TIMES_BOLD, 13, Font.BOLD, BaseColor.BLACK)));
                document.add(new Paragraph("                          POST OFFICE BOX 23, KUMASI",  FontFactory.getFont(FontFactory.TIMES_BOLD, 13, Font.BOLD, BaseColor.BLACK)));
                document.add(new Paragraph("                              "));
                document.add(new Paragraph("GENERAL MEETING RECIEPT", FontFactory.getFont(FontFactory.TIMES_BOLD, 13, Font.BOLD, BaseColor.BLUE)));
                document.add(new Paragraph(new java.util.Date().toString()));
                document.add(new Paragraph("****************************************************************************************************"));
                  
               
                   
                document.add(new Paragraph("     MEMBER DETAILS", FontFactory.getFont(FontFactory.TIMES_BOLD, 13, Font.BOLD, BaseColor.BLACK)));
                document.add(new Paragraph("-------------------------------------------------"));
                document.add(new Paragraph("MEMBER CODE:  "+ value2 , FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.PLAIN, BaseColor.BLACK)));
                document.add(new Paragraph("MEMBER FULL NAME:  " +value +"  "+ value1 , FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.PLAIN, BaseColor.BLUE)));
                document.add(new Paragraph("MEMBER HOME TOWN: "+ value3, FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.PLAIN, BaseColor.BLACK)));
             //   document.add(new Paragraph("FUNERAL OWNER: " , FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.PLAIN, BaseColor.BLACK)));
                document.add(new Paragraph("GENERAL MEETING CONT. TYPE : "+ rs.getString(4) , FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.PLAIN, BaseColor.BLACK)));
                document.add(new Paragraph("                "));
                document.add(new Paragraph("----------------------------------------------------"));
                document.add(new Paragraph("             "));
                document.add(new Paragraph("AMOUNT ₵ =  "+ rs.getString(5), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.PLAIN, BaseColor.BLACK))); 
                document.add(new Paragraph("            "));
                document.add(new Paragraph("BALANCE ₵ =  "+ rs.getString(2), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.PLAIN, BaseColor.BLACK)));
                document.add(new Paragraph("                "));
                document.add(new Paragraph("                "));
                document.add(new Paragraph("  Financial Secretary. : ", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.PLAIN, BaseColor.BLACK)));
                document.add(new Paragraph("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"));
                document.add(new Paragraph("    Mr. Alexander Nsia            "));
               
                
                document.close(); 
                
               }
               
             
              JOptionPane.showMessageDialog(null, " RECIEPT GENERATED SUCCESSFULLY");
              
              
          }  catch (Exception e){
              
              JOptionPane.showMessageDialog(null, e);
          }
            
            
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_print_recActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

           
      
        String value = l_name.getText();
        String value1 = f_name.getText();
        String value2 = searchme.getText();
        //String value3 = ht.getText();
       
        
        
        JFileChooser dailog = new JFileChooser();
        dailog.setSelectedFile(new File(value+" "+value1+" General Meeting Records"+".pdf"));
        int dialogResult = dailog.showSaveDialog(null);
        if (dialogResult == JFileChooser.APPROVE_OPTION) {
            String filepath = dailog.getSelectedFile().getPath();
      
           try{
           
               con = Connection1.ConnectDB();
               String sql = " Select * from general WHERE mem_id ='"+value2+"'";
               pst = con.prepareStatement(sql);
               rs = pst.executeQuery();
                
               Document document = new Document();
               PdfWriter.getInstance(document, new FileOutputStream(filepath));
               document.open();
               
               
               
                
                document.add(new Paragraph("                    DYNAMIC INTERNATIONAL CLUB, KUMASI BRANCH", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.BOLD, BaseColor.BLACK)));
                document.add(new Paragraph("                                POST OFFICE BOX 23, KUMASI", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.BOLD, BaseColor.BLACK)));
                document.add(new Paragraph("REF NO.................."));
                document.add(new Paragraph(" "));
                
                Paragraph p = new Paragraph();
                Chunk c = new Chunk("DATE / TIME:  ");
                p.add(c);
                p.add(new java.util.Date().toString());
                document.add(p);
                
               // document.add(new Paragraph(new java.util.Date().toString()));
                document.add(new Paragraph("****************************************************************************************************************"));
                document.add(new Paragraph(" PERSONAL GENERAL CONTRIBUTION RECORDS FOR "+value+" "+value1+"", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.BOLD, BaseColor.ORANGE)));
                document.add(new Paragraph("****************************************************************************************************************"));
                document.add(new Paragraph("  "));
                PdfPTable table = new PdfPTable(5);
                
                float[] columnWidths = new float [] {10,13,15,12,12};
                table.setWidths(columnWidths);
                
                
                table.setWidthPercentage(100);
                document.add(new Paragraph(" "));
                              
                table.addCell(new PdfPCell(new Paragraph("DYNAMIC CODE", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph("NAME OF MEMBER", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph("TYPE OF CONTRIBUTION", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph("AMOUNT GH₵", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph("DATE", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
                //table.addCell(new PdfPCell(new Paragraph("STATUS", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
               /// table.addCell(new PdfPCell(new Paragraph("TELEPHONE", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
               // table.addCell(new PdfPCell(new Paragraph("OCCUPATION", FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
                
                while (rs.next()){
                table.addCell(new PdfPCell(new Paragraph(rs.getString(2), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph(rs.getString(3), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph(rs.getString(4), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph(rs.getString(5), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph(rs.getString(6), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
                //table.addCell(new PdfPCell(new Paragraph(rs.getString(7), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
               // table.addCell(new PdfPCell(new Paragraph(rs.getString(9), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
                //table.addCell(new PdfPCell(new Paragraph(rs.getString(12), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
             
                
               // table.addCell(new PdfPCell(new Paragraph(rs.getString(17), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD))));
                
                }
                
      
                
                document.add(table);
                document.close();

       }catch (Exception ex){
           
       }
       JOptionPane.showMessageDialog(null, " MEMBER RECORD OF "
               + value +" CREATED");

    }        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        dispose();
        main m = new main();
        m.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {

            con=Connection1.ConnectDB();
            String sql = "INSERT INTO general"
            +"(mem_id,mem_name,contribution,amount,date)"
            +"values(?,?,?,?,?)";

            PreparedStatement pstm = con.prepareStatement(sql);

            pstm.setString(1, searchme.getText());

            pstm.setString(2, l_name.getText()+" " + f_name.getText());

            String c = con_cmb.getSelectedItem().toString();
            pstm.setString(3, c);

            pstm.setString(4, txt_amount.getText());

           
            pstm.setString(5, ((JTextField)dba.getDateEditor().getUiComponent()).getText());

           

            pstm.executeUpdate();

            JOptionPane.showMessageDialog(this, "YOUR CONTRIBUTION ADDED SUCCESSFULLY"," CONTRIBUTION",JOptionPane.ERROR_MESSAGE);
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void htActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_htActionPerformed

    private void con_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_cmbActionPerformed

        if (  con_cmb.getSelectedItem().equals("GIFT")){

            txt_amount.setText(" 500");
            
        }
        else if (  con_cmb.getSelectedItem().equals("BIRTHDAY")){

            txt_amount.setText(" 1000");
        }
        else if (  con_cmb.getSelectedItem().equals("DONATION")){

            txt_amount.setText(" 1500");
        }
        else if (  con_cmb.getSelectedItem().equals("LIFE PREMIUM")){

            txt_amount.setText("22500");
        }
        else if (  con_cmb.getSelectedItem().equals("FUNERAL")){

            txt_amount.setText(" ");
            loc_check.enable();
            int_check.enable();
        }
      else if (  con_cmb.getSelectedItem().equals("OTHER...")){

            txt_amount.setText("500");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_con_cmbActionPerformed

    private void txt_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_amountActionPerformed

    private void loc_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loc_checkActionPerformed

        txt_amount.setText("50");

        // TODO add your handling code here:
    }//GEN-LAST:event_loc_checkActionPerformed

    private void searchmeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchmeKeyTyped
char c=evt.getKeyChar();
      if (!(Character.isDigit(c)|| (c== KeyEvent.VK_SPACE)||(c== KeyEvent.VK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null, " PLEASE ENTER ONLY NUMBERS !!");
    }     
        
        // TODO add your handling code here:
    }//GEN-LAST:event_searchmeKeyTyped

    private void int_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int_checkActionPerformed
      txt_amount.setText("100");
        // TODO add your handling code here:
    }//GEN-LAST:event_int_checkActionPerformed

    private void loc_checkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loc_checkMouseEntered
   loc_check.disable();
        // TODO add your handling code here:
    }//GEN-LAST:event_loc_checkMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(meeting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(meeting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(meeting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(meeting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new meeting().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox con_cmb;
    private javax.swing.JTextField dat;
    private com.toedter.calendar.JDateChooser dba;
    private javax.swing.JTextField f_name;
    private javax.swing.JComboBox gender_cmb;
    private javax.swing.JTextField ht;
    private javax.swing.JRadioButton int_check;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField l_name;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JRadioButton loc_check;
    private javax.swing.JLabel lpic1;
    private javax.swing.JComboBox mt_cmb1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel4;
    private javax.swing.JButton print_rec;
    private javax.swing.JPanel search;
    private javax.swing.JTextField searchme;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTable v_table;
    private javax.swing.JComboBox yr_cmb;
    // End of variables declaration//GEN-END:variables

    private void section() {
 setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("dynamic.jpg")));
    }
}
